
NumPy("넘파이"라 읽는다)는 행렬이나 일반적으로 대규모 다차원 배열을 쉽게 처리할 수 있도록 지원하는 파이썬의 라이브러리이다. NumPy는 데이터 구조 외에도 수치 계산을 위해 효율적으로 구현된 기능을 제공한다
- 위키백과(https://ko.wikipedia.org/wiki/NumPy)


In [11]:
import numpy as np


a = np.array([ [1, 2], [3, 4], [5,6]])
b = np.array([6, 7, 8, 9, 10]) 
al = [1, 2, 3, 4, 5]


print (a ** 2)


[[ 1  4]
 [ 9 16]
 [25 36]]


In [13]:
print ( 10 **3)

1000


In [1]:
import numpy as np   ## pip install numpy

# Create a NumPy array
array = np.array([1, 2, 3, 4, 5])

# Perform basic operations
print("Original Array:", array)
print("Array + 2:", array + 2)  # Add 2 to each element
print("Array * 3:", array * 3)  # Multiply each element by 3
print("Mean of Array:", np.mean(array))  # Calculate the mean
print("Sum of Array:", np.sum(array))  # Calculate the sum

# Create a 2D array
matrix = np.array([[1, 2, 3], [4, 5, 6]])
print("\n2D Array (Matrix):\n", matrix)

# Transpose the matrix
print("Transposed Matrix:\n", matrix.T)

# Element-wise multiplication
print("Element-wise Multiplication:\n", matrix * 2)

Original Array: [1 2 3 4 5]
Array + 2: [3 4 5 6 7]
Array * 3: [ 3  6  9 12 15]
Mean of Array: 3.0
Sum of Array: 15

2D Array (Matrix):
 [[1 2 3]
 [4 5 6]]
Transposed Matrix:
 [[1 4]
 [2 5]
 [3 6]]
Element-wise Multiplication:
 [[ 2  4  6]
 [ 8 10 12]]


In [2]:
import numpy as np
 
list1 = [1, 2, 3, 4]
a = np.array(list1)
print(a.shape) # (4, )
 
b = np.array([[1,2,3],[4,5,6]])
print(b.shape) # (2, 3)
print(b[0,0])  # 1    

(4,)
(2, 3)
1


In [3]:
import pandas as pd

# Create a pandas DataFrame from the NumPy array 'b'
df = pd.DataFrame(b, columns=['Column1', 'Column2', 'Column3'])

# Add a new column to the DataFrame using the NumPy array 'a'
df['NewColumn'] = a[:df.shape[0]]  # Use slicing to match the number of rows

# Perform some operations on the DataFrame
df['Sum'] = df.sum(axis=1)  # Add a new column with the sum of each row

print("DataFrame created from NumPy array 'b':\n", df)

ModuleNotFoundError: No module named 'pandas'

In [4]:
!pip install pandas

   ---------------------------------------- 0.0/11.5 MB ? eta -:--:--
   ------------------- -------------------- 5.5/11.5 MB 23.9 MB/s eta 0:00:01
   ------------------------------- -------- 9.2/11.5 MB 19.7 MB/s eta 0:00:01
   ---------------------------------------  11.3/11.5 MB 17.6 MB/s eta 0:00:01
   ---------------------------------------- 11.5/11.5 MB 15.0 MB/s eta 0:00:00
