Array Creation
np.array(): Creates an array from a list or tuple.
np.zeros(shape): Creates an array filled with zeros.
np.ones(shape): Creates an array filled with ones.
np.arange(start, stop, step): Creates an array with evenly spaced values.
np.linspace(start, stop, num): Creates an array with a specified number of evenly spaced values.
np.eye(n): Creates an identity matrix.

Array Manipulation
np.reshape(array, new_shape): Reshapes an array without changing its data.
np.transpose(array): Transposes the array (flips rows and columns).
np.concatenate((a, b), axis): Joins arrays along a specified axis.
np.split(array, indices_or_sections): Splits an array into multiple sub-arrays.
np.flatten(): Flattens a multi-dimensional array into a 1D array.
Mathematical Operations
np.sum(array, axis): Computes the sum along a specified axis.
np.mean(array, axis): Computes the mean along a specified axis.
np.median(array): Computes the median.
np.std(array): Computes the standard deviation.
np.dot(a, b): Computes the dot product of two arrays.
np.sqrt(array): Computes the square root of each element.

Indexing and Slicing
array[index]: Accesses elements using indices.
array[start:stop:step]: Slices the array.
np.where(condition): Returns indices where the condition is true.
np.take(array, indices): Extracts elements at specified indices.
Random Number Generation
np.random.rand(d0, d1, ...): Generates random numbers in [0, 1).
np.random.randint(low, high, size): Generates random integers.
np.random.normal(mean, std, size): Generates random numbers from a normal distribution.

Logical Operations
np.all(array, axis): Checks if all elements are true.
np.any(array, axis): Checks if any element is true.
np.logical_and(a, b): Performs element-wise logical AND.
np.logical_or(a, b): Performs element-wise logical OR.
These methods are just the tip of the iceberg! NumPy is incredibly versatile and powerful for numerical computations. Let me know if you'd like examples or further details on any of these! 😊



In [ ]:
# Array Creation
# np.array(): Creates an array from a list or tuple.
# np.zeros(shape): Creates an array filled with zeros.
# np.ones(shape): Creates an array filled with ones.
# np.arange(start, stop, step): Creates an array with evenly spaced values.
# np.linspace(start, stop, num): Creates an array with a specified number of evenly spaced values.
# np.eye(n): Creates an identity matrix.

# pip install numpy
# shape, 
import numpy # as np


arr_org  = numpy.array([ [1, 2], [3, 4], [5,6]])
arr_zero = numpy.zeros([2,4,4])
arr_zero_like  = numpy.zeros_like(arr_org)
# numpy.zeros example
arr_zeros = numpy.zeros(arr_org.shape)
print("Array of zeros with shape", arr_org.shape, ":\n", arr_zeros)

print(arr_org)
print(arr_zero)
print(arr_zero_like)
print(arr_zero.shape)



Array of zeros with shape (3, 2) :
 [[0. 0.]
 [0. 0.]
 [0. 0.]]
[[1 2]
 [3 4]
 [5 6]]
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
[[0 0]
 [0 0]
 [0 0]]
(2, 4, 4)
