In [ ]:
import numpy as np


a = np.zeros((2,2))
b = np.ones((2,2))
c = np.full((6,2), 7)

print(a, b,c,  sep='\n\n')

[[0. 0.]
 [0. 0.]]

[[1. 1.]
 [1. 1.]]

[[7 7]
 [7 7]
 [7 7]
 [7 7]
 [7 7]
 [7 7]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
# 단위행렬
# 주대각선은 1이고 나머지는 0인 정사각 행렬

d = np.eye( 10) # 단위행렬

print(d)


[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


: 