In [ ]:
import numpy as np


a = np.arange(20).reshape(5, 4)
print(a)
print(a[1][2])


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
6


In [ ]:
b = np.array([[1, 2], [3, 4]])
print(b)
print(np.nan)



# vs list

c = [1,2,3,4,5]
# print(type(c))
c[1] = c[1] * 2
print(c[1])


[[1 2]
 [3 4]]
nan
0
4


In [ ]:
## numpuy 함수

## array 생성
arr2 = np.array([[1, 2, 3, 4, 5], [2,3,4,5,6]] )  ## 2차원 배열

arr3 = np.array([[1, 2, 3, 4, 5], [2,3,4,5,6], [3,4,5,6,7] ] )  ## 3차원 배열

print('arr2=', arr2)
print('arr3=', arr3)


print( np.mean(arr2) )  ## 평균
print( np.median(arr2) )  ## 중앙값
print( np.std(arr2) )  ## 표준편차
print( np.var(arr2) )  ## 분산

print( np.sum(arr2) )  ## 합계
print( np.max(arr3) )  ## 최대값
print( np.min(arr2) )  ## 최소값
print( np.argmax(arr2) )  ## 최대값의 인덱스
print( np.argmin(arr2) )  ## 최소값의 인덱스


In [78]:
# pandas
# pandas는 데이터 분석을 위한 라이브러리로, 데이터프레임(DataFrame)이라는 자료구조를 사용하여 데이터를 다룬다.
import numpy as np
import pandas as pd

# a = np.random.rand(3, 4)  # 3x4 행렬 생성
# print(a)

b = np.random.randint(1, 10, (3, 4))  # 1부터 10까지의 정수로 이루어진 3x4 행렬 생성
# print(b)


# d = pd.DataFrame(b, columns=['A', 'B', 'C', 'D'], index=['row1', 'row2', 'row3'])
df = pd.DataFrame(b, columns=['A', 'B', 'C', 'D'])
# df.index = ['row1', 'row2', 'row3']  
# print(d['A'])  # 'A' 열 선택

# da = d['A']
# print(da)  # 'A' 열 선택



df['합계'] = df['A'] +  df['B'] + df['C'] +  df['D']
df['평균'] = round(df['합계'] / 4, 2)
df['비고'] = np.nan

print(df['비고'])
# df

# df[ df['평균'] > 5]
# print(df2)


df2 = df[ df.평균 > 5]
print(df2)

# df

0   NaN
1   NaN
2   NaN
Name: 비고, dtype: float64
   A  B  C  D  합계    평균  비고
1  2  6  7  8  23  5.75 NaN
2  8  9  5  7  29  7.25 NaN


결측값 np.nan


In [ ]:
# 결측값 다루기
# inplace = True : 원본 데이터프레임을 수정
# inplace = False : 원본 데이터프레임을 수정하지 않고 새로운 데이터프레임을 반환

np.dropna(df, axis=0, inplace=True)  # 결측값이 있는 행 삭제
np.fillna(df, 0, inplace=True)  # 결측값을 0으로 대체


In [ ]:
# 멀티 인덱스
# 멀티 인덱스는 데이터프레임의 행 인덱스에 여러 개의 레벨을 추가하여 계층적인 구조를 만드는 방법이다.
# 멀티 컬럼


